
#Adaptive Performance Tweaks: Spawn
["Custom Spawn Config"]
	customEnabled = false
	customId = "custom_config"
	#Range: 1 ~ 64
	customMaxPassiveMobsPerPlayer = 2
	#Range: 1 ~ 512
	customMaxPassiveMobsPerWorld = 16
	#List of passive Mobs to optimize in the format ["minecraft:bat", ..]
	customPassiveMobsList = []
	#Range: 1 ~ 64
	customMaxNeutralMobsPerPlayer = 2
	#Range: 1 ~ 512
	customMaxNeutralMobsPerWorld = 16
	#List of neutral Mobs to optimize in the format ["minecraft:bee", "minecraft:cat", ..]
	customNeutralMobsList = []
	#Range: 1 ~ 64
	customMaxHostileMobsPerPlayer = 2
	#Range: 1 ~ 512
	customMaxHostileMobsPerWorld = 16
	#List of hostile Mobs to optimize in the format ["minecraft:blaze", "minecraft:cave_spider", ..]
	customHostileMobsList = []

