name = "Technical Electrical Final Frontiers [Forge] - 1.18.2"
author = "Waddon1"
version = "1.1.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f582e574b9bc8b85877c88540b249618023b5ac2d4a6a46db4f302840da2976c"

[versions]
forge = "40.0.52"
minecraft = "1.18.2"
