name = "Technical Electrical Final Frontiers [Forge] - 1.18.2"
author = "Waddon1"
version = "0.3.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0042a7efe40a2bdb05528e5afecac1b4cd30e2b2b32fc8d1f82b545d3dc7d764"

[versions]
forge = "40.0.52"
minecraft = "1.18.2"
