name = "Technical Electrical Final Frontiers [Forge] - 1.18.2"
author = "Waddon1"
version = "1.1.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d6e58d90e2b79d1eec31940e32014b4d80f9addcf6a9ab744ed4d050b5f9612b"

[versions]
forge = "40.0.52"
minecraft = "1.18.2"
