name = "Technical Electrical Final Frontiers [Forge] - 1.18.2"
author = "Waddon1"
version = "0.2.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15b51ce9bb7c22a5c375e65e4474414fb735712ecb1eb8f88475b2bf71fa3679"

[versions]
forge = "40.0.49"
minecraft = "1.18.2"
