name = "Technical Electrical Final Frontiers [Forge] - 1.18.2"
author = "Waddon1"
version = "0.3.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b39eb3c280bd3aeed5fef9f1b805bc5330271f86a5f8c58f062a6719d147de4d"

[versions]
forge = "40.0.52"
minecraft = "1.18.2"
