name = "Technical Electrical Final Frontiers"
version = "0.1.7"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7bda85ca014e9630b6fb596f4832a0d40c9e9005002b63e59a2858b412e9e009"

[versions]
forge = "40.0.48"
minecraft = "1.18.2"
