name = "Technical Electrical Final Frontiers [Forge] - 1.18.2"
author = "Waddon1"
version = "1.8.1"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "88293fd73905973d9722baab08bf096527b82d3ec793d096a3a0b024cb9fb14b"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
