name = "Technical Electrical Final Frontiers [Forge] - 1.18.2"
author = "Waddon1"
version = "1.3.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4c9e7d2e6320a2e0d5deb16617de3dc0752011639bf81d364fb0ccb5275ece62"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
