name = "Technical Electrical Final Frontiers [Forge] - 1.18.2"
author = "Waddon1"
version = "0.2.4"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0d302f8babbee74ae578e6884a2f3b66a2e4566ebc6df1559e8e09f9b9ac0517"

[versions]
forge = "40.0.49"
minecraft = "1.18.2"
