name = "Technical Electrical Final Frontiers [Forge] - 1.18.2"
author = "Waddon1"
version = "0.3.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6df87f56327d6391220c041e940e20f91752d513c621368cc0879fa55977aad"

[versions]
forge = "40.0.52"
minecraft = "1.18.2"
