name = "Technical Electrical Final Frontiers [Forge] - 1.18.2"
author = "Waddon1"
version = "0.2.5"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ff97502e2fb1ec2d9fe87de63a26fa0bfc389639e8e5095d3b1e667eb603b4cc"

[versions]
forge = "40.0.49"
minecraft = "1.18.2"
