name = "Technical Electrical Final Frontiers [Forge] - 1.18.2"
author = "Waddon1"
version = "0.2.6"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "de8cec738b12162d839ee7ae83d00aa1e4129192767a4d140fbe75805f502cc0"

[versions]
forge = "40.0.49"
minecraft = "1.18.2"
