name = "Technical Electrical Final Frontiers [Forge] - 1.18.2"
author = "Waddon1"
version = "1.0.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2cf8cdc46e727ade08e5c191647ee9372c00405734bc9fbf197050d651e4b0b3"

[versions]
forge = "40.0.52"
minecraft = "1.18.2"
