name = "Technical Electrical Final Frontiers [Forge] - 1.18.2"
author = "Waddon1"
version = "1.4.0"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8c5b1da536b99c3aeb5b4018406fe048192b2474c6eae043348dfc242237397b"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
