name = "Technical Electrical Final Frontiers"
version = "0.1.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0850a3cf6f60db0ad12e67ca12496e2a2eda7ed441d06ca0f7031a38cd6ca196"

[versions]
forge = "40.0.46"
minecraft = "1.18.2"
