name = "Technical Electrical Final Frontiers [Forge] - 1.18.2"
author = "Waddon1"
version = "0.4.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6e0f7905e36da41df64b57ff0f92122dae0bd3d885c2ad81167a625cfcdd95f8"

[versions]
forge = "40.0.52"
minecraft = "1.18.2"
