name = "Technical Electrical Final Frontiers [Forge] - 1.18.2"
author = "Waddon1"
version = "0.3.3"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "74510f065841b05328367b249796176d69a70915a538bd5a17702f73b3e1e1a2"

[versions]
forge = "40.0.52"
minecraft = "1.18.2"
