name = "Technical Electrical Final Frontiers [Forge] - 1.18.2"
author = "Waddon1"
version = "1.11.2"
pack-format = "packwiz:1.0.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "442054f27b25e35d6c645064002f7915a3b6d79009ce8f463e43eeb7c583b92f"

[versions]
forge = "40.1.0"
minecraft = "1.18.2"
