
[client]
	#TODO
	disableColoredCableRecipesInJEI = true
	showFacadesInJEI = true
	#TODO
	enableEffects = true
	#TODO
	useTerminalUseLargeFont = false
	#TODO
	useColoredCraftingStatus = true
	#Power unit shown in AE UIs
	#Allowed Values: AE, RF
	PowerUnit = "AE"
	#Show debugging GUI overlays
	showDebugGuiOverlays = false
	#Show a preview of part and facade placement
	showPlacementPreview = true

	[client.terminals]
		#Should tooltips be searched. Performance impact
		#Allowed Values: YES, NO, UNDECIDED
		searchTooltips = "YES"
		#Allowed Values: TALL, FULL, SMALL
		terminalStyle = "TALL"
		#Allowed Values: DEFAULT, REMEMBER_SEARCH, AUTO_FOCUS, AUTO_FOCUS_AND_REMEMBER_SEARCH, JEI, REI
		terminalSearchMode = "DEFAULT"

