
#Common configuration settings. Most other configuration can be found in the world (server)configuration folder
[common]
	#Check for new versions of Vampirism on startup
	versionCheck = true
	#Send mod version, MC version and mod count to mod author
	collectStats = true

	[common.internal]
		#INTERNAL - Set to 'never' if you don't want to be notified about integration mods
		integrationsNotifier = ""
		#INTERNAL
		optifineBloodvisionWarning = false

#Affects all worlds. This is only considered on server (or in singleplayer), but Forge requires us to put it here
[common-server]
	#Whether glass bottles should be automatically be converted to blood bottles when needed
	autoConvertGlassBottles = true
	#If enabled adds a craftable umbrella that can be used to slowly walk though sunlight without taking damage
	umbrella = false

	[common-server.mobspawn]
		#Vampire spawn chance/weight (e.g. Zombie: 100). Does not affect vampire forest.
		#Range: 0 ~ 100000
		vampireSpawnChance = 80
		#Advanced vampire spawn chance/weight (e.g. Zombie: 100). Does not affect vampire forest.
		#Range: 0 ~ 100000
		advancedVampireSpawnChance = 26
		#Hunter spawn chance. By default they only spawn in tent camps, but you can enable global spawn here.
		#Range: 0 ~ 10000
		hunterSpawnChance = 75
		#Advanced hunter spawn chance. By default they only spawn in large tent camps, but you can enable global spawn here.
		#Range: 0 ~ 100000
		advancedHunterSpawnChance = 0
		#Vampire baron spawn chance in vampire forest (reference vampire in forest: 35)
		#Range: 0 ~ 10000
		baronSpawnChance = 10

	#Settings here require a game restart
	[common-server.world]
		#Whether to inject the vampire forest into the default overworld generation and to replace some Taiga areas
		addVampireForestToOverworld = false
		#Control hunter camp generation. If disabled you should set hunterSpawnChance to 75.
		enableHunterTentGeneration = false
		#Use the vanilla campfire block instead of Vampirism's much cooler one
		useVanillaCampfire = true

		[common-server.world.village]
			#Weight of the Totem Building inside the Village
			#Range: > 0
			totemWeight = 20
			#Chance for a totem to have a faction after generation
			#Range: 0.0 ~ 1.0
			villageTotemFactionChance = 0.6
			#Weight of the Hunter Trainer Building inside the Village
			#Range: > 0
			villageHunterTrainerWeight = 150
			#Whether village Temples should be replaced with versions that contain church altars.
			villageReplaceTemples = true

