
[behaviour]
	#Determines the range quantum locked entities will check if the player is looking in
	#Range: 1 ~ 100
	stalk_range = 65
	#If enabled alongside the mobGriefing gamerule, angels will interact with blocks that emit light
	block_breaking = true

[damage]
	#Hurt
	#Allowed Values: PICKAXE, PICKAXE_AND_GENERATOR, NONE, GENERATOR, ANYTHING
	hurt_type = "PICKAXE_AND_GENERATOR"

[teleporting]
	#Determines the range that a player can be teleported from their current location
	#Range: > 1
	teleport_range = 200
	#Determines the chance a player will be teleported
	#Range: 1 ~ 100
	teleport_chance = 50
	#A list of Dimensions that angels cannot teleport players to
	banned_dimensions = ["minecraft:the_end"]

