
#Adaptive Performance Tweaks: Gamerules
[General]
	#The time after a high to low load change is considered as valid. High loads are always considered immediately.
	#Range: 1 ~ 90
	timeBetweenUpdates = 30

["Entity Cramming"]
	#Enable/Disable dynamic entity cramming adjustments.
	entityCrammingEnabled = true
	#Defines the min. numbers of mob singularity on a single block.
	#Range: 0 ~ 64
	minEntityCramming = 5
	#Defines the max. numbers of mob singularity on a single block.
	#Range: 1 ~ 64
	maxEntityCramming = 24
	#Defines the min. numbers of mob singularity on a single block, in the case MineColonies is installed.
	#Range: 16 ~ 64
	minEntityCrammingMineColonies = 16

["Random Tick Speed"]
	#Enable/Disable dynamic random tick speed adjustments.
	randomTickSpeedEnabled = true
	#Defines the max. speed of crops grow, leaf decay, redstone, ... per chunk
	#Range: 1 ~ 256
	randomTickSpeed = 3

[Raids]
	#Enable/Disable dynamic raids adjustments.
	raidsEnabled = true

[Insomnia]
	#Enable/Disable insomnia (phantoms) adjustments.
	insomniaEnabled = true

["Patrol Spawning"]
	#Enable/Disable patrol spawning adjustments.
	patrolSpawningEnabled = true

["Trader Spawning"]
	#Enable/Disable trader spawning adjustments.
	traderSpawningEnabled = true

["Warden Spawning"]
	#Enable/Disable warden spawning adjustments.
	wardenSpawningEnabled = true

