name = "Applied Energistics 2 Wireless Terminals"
filename = "AE2WTLib-11.0.0-alpha.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3748/905/AE2WTLib-11.0.0-alpha.2.jar"
hash-format = "sha1"
hash = "15193601e9ba9e940478dbd680b8a4727d24bd51"

[update]
[update.curseforge]
file-id = 3748905
project-id = 459929
