name = "Applied Mekanistics"
filename = "Applied-Mekanistics-1.1.5-beta.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3778/47/Applied-Mekanistics-1.1.5-beta.jar"
hash-format = "sha1"
hash = "76aaf0ff70383ce6c33922e949497d6d4cdef25b"

[update]
[update.curseforge]
file-id = 3778047
project-id = 574300
