name = "Applied Mekanistics"
filename = "Applied-Mekanistics-1.1.4-beta.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3770/541/Applied-Mekanistics-1.1.4-beta.jar"
hash-format = "sha1"
hash = "93c63847008684cb6343194188e430856bab8347"

[update]
[update.curseforge]
file-id = 3770541
project-id = 574300
