name = "Architectury API (Forge)"
filename = "architectury-4.2.49.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3755/528/architectury-4.2.49.jar"
hash-format = "sha1"
hash = "f684a072b548c7a4a88312a2277faae4059e7727"

[update]
[update.curseforge]
file-id = 3755528
project-id = 419699
