name = "Architectury API (Forge)"
filename = "architectury-4.2.48.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3752/163/architectury-4.2.48.jar"
hash-format = "sha1"
hash = "99f3a2296d93ae3d944631d81a11ad3deef066f1"

[update]
[update.curseforge]
file-id = 3752163
project-id = 419699
