name = "Architectury API (Forge)"
filename = "architectury-4.2.50.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3758/442/architectury-4.2.50.jar"
hash-format = "sha1"
hash = "0c880ce88a17ac957bfdd7822e7d8925dae9c718"

[update]
[update.curseforge]
file-id = 3758442
project-id = 419699
