name = "Architectury API (Fabric/Forge)"
filename = "architectury-4.4.60.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3786/591/architectury-4.4.60.jar"
hash-format = "sha1"
hash = "86f0c2060f8c9b929a30e877232e8e4dc9d1fd54"

[update]
[update.curseforge]
file-id = 3786591
project-id = 419699
