name = "Ars Nouveau"
filename = "ars_nouveau-1.18.2-2.3.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3757/209/ars_nouveau-1.18.2-2.3.3.jar"
hash-format = "sha1"
hash = "737d5f0d28c1104cb828ce2a8eb56a26d4af53e7"

[update]
[update.curseforge]
file-id = 3757209
project-id = 401955
