name = "Ars Nouveau"
filename = "ars_nouveau-1.18.2-2.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3765/49/ars_nouveau-1.18.2-2.4.0.jar"
hash-format = "sha1"
hash = "e5913523225fd3c4c866a7b638c5523300a58793"

[update]
[update.curseforge]
file-id = 3765049
project-id = 401955
