name = "Assembly Lines"
filename = "Assembly Line-1.18.2-0.4.2-3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3779/70/Assembly%20Line-1.18.2-0.4.2-3.jar"
hash-format = "sha1"
hash = "5e5953740f27180920c1c1b9e8f1804997ef3bb4"

[update]
[update.curseforge]
file-id = 3779070
project-id = 404360
