name = "Audio Extension for FancyMenu [Forge]"
filename = "fm_audio_extension_forge_1.0.0_MC_1.18-1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3754/908/fm_audio_extension_forge_1.0.0_MC_1.18-1.18.2.jar"
hash-format = "sha1"
hash = "324bd0f951626d77dd5162c958bfe6e79547e23a"

[update]
[update.curseforge]
file-id = 3754908
project-id = 613067
