name = "Ballistix"
filename = "Ballistix-1.18.2-0.5.3-2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3771/283/Ballistix-1.18.2-0.5.3-2.jar"
hash-format = "sha1"
hash = "a1a40251436563da0a4492fe434ac2e3f102f1ac"

[update]
[update.curseforge]
file-id = 3771283
project-id = 443915
