name = "Ballistix"
filename = "Ballistix-1.18.2-0.5.3-0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3751/866/Ballistix-1.18.2-0.5.3-0.jar"
hash-format = "sha1"
hash = "533b90b7bb0d382228e7a4a78b2d4b56733ab22c"

[update]
[update.curseforge]
file-id = 3751866
project-id = 443915
