name = "Balm (Forge Edition)"
filename = "balm-3.0.3+0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3767/671/balm-3.0.3+0.jar"
hash-format = "sha1"
hash = "5adac76aa814044a8de5ca26e590bc34a5ba5c0f"

[update]
[update.curseforge]
file-id = 3767671
project-id = 531761
