name = "Better Fps - Render Distance[Forge]"
filename = "betterfpsdist-1.18.2-1.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3750/13/betterfpsdist-1.18.2-1.5.jar"
hash-format = "sha1"
hash = "00a1e55481f45aa43ab5f72ba146b81c770568d5"

[update]
[update.curseforge]
file-id = 3750013
project-id = 551520
