name = "Better Biome Blend"
filename = "betterbiomeblend-1.18.2-1.3.4-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3692/464/betterbiomeblend-1.18.2-1.3.4-forge.jar"
hash-format = "sha1"
hash = "a5d6dc728d495a2720ff299fd1d4069324ba4d67"

[update]
[update.curseforge]
file-id = 3692464
project-id = 446253
