name = "Beyond Earth (Forge)"
filename = "Beyond-Earth-1.18.2-6.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3751/153/Beyond-Earth-1.18.2-6.1.jar"
hash-format = "sha1"
hash = "9414930bbe0c61ebb0d42169da9ca11a80894fa8"

[update]
[update.curseforge]
file-id = 3751153
project-id = 377448
