name = "Blastcraft mod"
filename = "Blastcraft-1.18.2-0.2.7-0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3751/865/Blastcraft-1.18.2-0.2.7-0.jar"
hash-format = "sha1"
hash = "3d4b86b979dbd69eea14df3a1b59360a3fd26d45"

[update]
[update.curseforge]
file-id = 3751865
project-id = 405322
