name = "Bookshelf"
filename = "Bookshelf-Forge-1.18.2-13.0.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3750/646/Bookshelf-Forge-1.18.2-13.0.12.jar"
hash-format = "sha1"
hash = "5793d4ba6eecc98f3bf8539d9ce867c8cc42929d"

[update]
[update.curseforge]
file-id = 3750646
project-id = 228525
