name = "Bookshelf"
filename = "Bookshelf-Forge-1.18.2-13.0.13.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3753/798/Bookshelf-Forge-1.18.2-13.0.13.jar"
hash-format = "sha1"
hash = "a1784926163dbe87e60c5153558cdbbb4cac7529"

[update]
[update.curseforge]
file-id = 3753798
project-id = 228525
