name = "Bookshelf"
filename = "Bookshelf-Forge-1.18.2-13.0.11.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3741/98/Bookshelf-Forge-1.18.2-13.0.11.jar"
hash-format = "sha1"
hash = "e509fba19b6c94149bc6397fdb5511c447eb503b"

[update]
[update.curseforge]
file-id = 3741098
project-id = 228525
