name = "Botania"
filename = "Botania-1.18.2-431.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3755/269/Botania-1.18.2-431.jar"
hash-format = "sha1"
hash = "60c239b58b2250c3bed1b6bf8f00853da9f57fa0"

[update]
[update.curseforge]
file-id = 3755269
project-id = 225643
