name = "Client Tweaks"
filename = "clienttweaks-forge-1.18.1-7.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3666/468/clienttweaks-forge-1.18.1-7.1.0.jar"
hash-format = "sha1"
hash = "1d2308ceaad544e2ba389e677fe3f9aee3a95a61"

[update]
[update.curseforge]
file-id = 3666468
project-id = 251407
