name = "Cloth Config API (Forge)"
filename = "cloth-config-6.2.57-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3641/133/cloth-config-6.2.57-forge.jar"
hash-format = "sha1"
hash = "fe21430bf2daf2ce2b1f6f7e2c01b07ba9d50642"

[update]
[update.curseforge]
file-id = 3641133
project-id = 348521
