name = "Cloth Config API (Fabric/Forge)"
filename = "cloth-config-6.2.62-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3782/776/cloth-config-6.2.62-forge.jar"
hash-format = "sha1"
hash = "1da6c984afef261cd5484ede8685abfe5242198b"

[update]
[update.curseforge]
file-id = 3782776
project-id = 348521
