name = "Clumps"
filename = "Clumps-forge-1.18.2-8.0.0+8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3757/581/Clumps-forge-1.18.2-8.0.0+8.jar"
hash-format = "sha1"
hash = "09f702445fb8ec8954318747c282ca84c093a63b"

[update]
[update.curseforge]
file-id = 3757581
project-id = 256717
