name = "Clumps"
filename = "Clumps-forge-1.18.2-8.0.0+7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3672/163/Clumps-forge-1.18.2-8.0.0+7.jar"
hash-format = "sha1"
hash = "59fa79c70016f02a89601c775c5f35376a70ed16"

[update]
[update.curseforge]
file-id = 3672163
project-id = 256717
