name = "Compact Machines"
filename = "compactmachines-4.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3758/773/compactmachines-4.2.0.jar"
hash-format = "sha1"
hash = "ce3bb4cd4235422e43b23f2339e2f55812918032"

[update]
[update.curseforge]
file-id = 3758773
project-id = 224218
