name = "Controlling"
filename = "Controlling-forge-1.18.2-9.0+19.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3758/406/Controlling-forge-1.18.2-9.0+19.jar"
hash-format = "sha1"
hash = "1d132397933e3553d4dca886b7331faafc93d814"

[update]
[update.curseforge]
file-id = 3758406
project-id = 250398
