name = "Cooking for Blockheads"
filename = "cookingforblockheads-forge-1.18.2-12.0.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3684/744/cookingforblockheads-forge-1.18.2-12.0.0.jar"
hash-format = "sha1"
hash = "b3213e78886d737efbd3a1c76bc0431c4c160615"

[update]
[update.curseforge]
file-id = 3684744
project-id = 231484
