name = "CraftPresence"
filename = "CraftPresence-Forge-1.18.2-Release-1.8.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3669/97/CraftPresence-Forge-1.18.2-Release-1.8.8.jar"
hash-format = "sha1"
hash = "8596d047ed98dce00811ea86ebd782d9aeb53b49"

[update]
[update.curseforge]
file-id = 3669097
project-id = 297038
