name = "Create Crafts & Additions"
filename = "createaddition-1.18.2-20220417a.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3756/141/createaddition-1.18.2-20220417a.jar"
hash-format = "sha1"
hash = "27a949ba8aff8175a8e95971ecad84497a65eca2"

[update]
[update.curseforge]
file-id = 3756141
project-id = 439890
