name = "Create Crafts & Additions"
filename = "createaddition-1.18.2-20220424a.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3766/3/createaddition-1.18.2-20220424a.jar"
hash-format = "sha1"
hash = "32e9e02b458a09f2ccb285232d0d5bd730ce4d85"

[update]
[update.curseforge]
file-id = 3766003
project-id = 439890
