name = "Create Crafts & Additions"
filename = "createaddition-1.18.2-20220409a.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3741/569/createaddition-1.18.2-20220409a.jar"
hash-format = "sha1"
hash = "f9c8bbdb951447273926c4bff6148b56b4cda58f"

[update]
[update.curseforge]
file-id = 3741569
project-id = 439890
