name = "Create"
filename = "create-mc1.18.2_v0.4.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3737/418/create-mc1.18.2_v0.4.1.jar"
hash-format = "sha1"
hash = "47f01160e2650c6d63c0d8cde2f72cee39d313f3"

[update]
[update.curseforge]
file-id = 3737418
project-id = 328085
