name = "Cucumber Library"
filename = "Cucumber-1.18.2-5.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3686/400/Cucumber-1.18.2-5.1.0.jar"
hash-format = "sha1"
hash = "e9288e01f28e9db74891bfbf6ea3dad627c0cfaa"

[update]
[update.curseforge]
file-id = 3686400
project-id = 272335
