name = "Cyclic"
filename = "Cyclic-1.18.2-1.7.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3777/95/Cyclic-1.18.2-1.7.0.jar"
hash-format = "sha1"
hash = "6baac34f04ac1afe253d2ecbfaeb110d72ad65d5"

[update]
[update.curseforge]
file-id = 3777095
project-id = 239286
