name = "Default Options"
filename = "defaultoptions-forge-1.18.1-14.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3630/249/defaultoptions-forge-1.18.1-14.1.0.jar"
hash-format = "sha1"
hash = "0357cf5eda58d25252d32af50d1bc8c857633051"

[update]
[update.curseforge]
file-id = 3630249
project-id = 232131
