name = "Drippy Loading Screen [Forge]"
filename = "drippyloadingscreen_forge_1.5.1_MC_1.18-1.18.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3630/870/drippyloadingscreen_forge_1.5.1_MC_1.18-1.18.1.jar"
hash-format = "sha1"
hash = "fb282d04d3eedc9e0fbb8bf664cab9d977b15a85"

[update]
[update.curseforge]
file-id = 3630870
project-id = 511770
