name = "Dynamic View[Forge/Fabric]"
filename = "dynview-1.18.2-2.7.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3740/656/dynview-1.18.2-2.7.jar"
hash-format = "sha1"
hash = "43e4c4ba4ef8d62997a71333e67693839cd0943c"

[update]
[update.curseforge]
file-id = 3740656
project-id = 366140
