name = "Electrodynamics"
filename = "Electrodynamics-1.18.2-0.6.3-8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3775/452/Electrodynamics-1.18.2-0.6.3-8.jar"
hash-format = "sha1"
hash = "cfd914b279c98aa132d85a26e70b25e321d99bcb"

[update]
[update.curseforge]
file-id = 3775452
project-id = 316867
