name = "Electrodynamics"
filename = "Electrodynamics-1.18.2-0.6.3-1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3768/740/Electrodynamics-1.18.2-0.6.3-1.jar"
hash-format = "sha1"
hash = "5bd28d41ecc9a31a2ecc614e827d77dc8b086ece"

[update]
[update.curseforge]
file-id = 3768740
project-id = 316867
