name = "Enchantment Descriptions"
filename = "EnchantmentDescriptions-Forge-1.18.2-10.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3754/812/EnchantmentDescriptions-Forge-1.18.2-10.0.3.jar"
hash-format = "sha1"
hash = "37bd370c7d13417cda0530f7c2d0d69f3ddd5d0a"

[update]
[update.curseforge]
file-id = 3754812
project-id = 250419
