name = "Entity Culling Fabric/Forge"
filename = "entityculling-forge-mc1.18-1.5.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3743/929/entityculling-forge-mc1.18-1.5.1.jar"
hash-format = "sha1"
hash = "fbf6368cd26d878ce3d75e899f039a1e51fa49a3"

[update]
[update.curseforge]
file-id = 3743929
project-id = 448233
