name = "Extreme Reactors"
filename = "ExtremeReactors2-1.18.2-2.0.42.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3768/543/ExtremeReactors2-1.18.2-2.0.42.jar"
hash-format = "sha1"
hash = "43b4912cfcbee763a219db75cd3ad4441216e21b"

[update]
[update.curseforge]
file-id = 3768543
project-id = 250277
