name = "Faithful 64x"
filename = "Faithful 64x beta 4.zip"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3751/500/Faithful%2064x%20beta%204.zip"
hash-format = "sha1"
hash = "069179d7580f6237801b2da6324df68a96655c2c"

[update]
[update.curseforge]
file-id = 3751500
project-id = 419139
