name = "FallingTree (Forge&Fabric)"
filename = "FallingTree-1.18.2-3.5.0b1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3740/503/FallingTree-1.18.2-3.5.0b1.jar"
hash-format = "sha1"
hash = "9f14c704961e5b7204c812f85ee66bc4bb9819bc"

[update]
[update.curseforge]
file-id = 3740503
project-id = 349559
