name = "Fancy: GUI Overhaul"
filename = "Fancy, GUI Overhaul v0.1.0.zip"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3781/247/Fancy,%20GUI%20Overhaul%20v0.1.0.zip"
hash-format = "sha1"
hash = "b28c5f9958992dc60cf084b8a6a1c12a2b7e4c26"

[update]
[update.curseforge]
file-id = 3781247
project-id = 620903
