name = "Farming for Blockheads"
filename = "farmingforblockheads-forge-1.18.2-10.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3710/119/farmingforblockheads-forge-1.18.2-10.0.1.jar"
hash-format = "sha1"
hash = "80b95be13c7b039aad5d4bd931d22ee67f38b3ca"

[update]
[update.curseforge]
file-id = 3710119
project-id = 261924
