name = "Farsight [Forge]"
filename = "farsight-1.18.2-1.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3752/368/farsight-1.18.2-1.8.jar"
hash-format = "sha1"
hash = "fdc0722ad833279272d8c428b191f5e009944ec5"

[update]
[update.curseforge]
file-id = 3752368
project-id = 495693
