name = "FastWorkbench"
filename = "FastWorkbench-1.18.2-6.0.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3717/873/FastWorkbench-1.18.2-6.0.2.jar"
hash-format = "sha1"
hash = "a8225d92bf202e95dc21b56275718efa91d5cdf2"

[update]
[update.curseforge]
file-id = 3717873
project-id = 288885
