name = "Fast Leaf Decay"
filename = "FastLeafDecay-28.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3693/140/FastLeafDecay-28.jar"
hash-format = "sha1"
hash = "1005968a5f60863168156efbf0ed7e05137d6ab2"

[update]
[update.curseforge]
file-id = 3693140
project-id = 230976
