name = "FerriteCore (Forge)"
filename = "ferritecore-4.2.1-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3767/288/ferritecore-4.2.1-forge.jar"
hash-format = "sha1"
hash = "ba3071bf50a8ffae349b7eca514415014e939267"

[update]
[update.curseforge]
file-id = 3767288
project-id = 429235
