name = "FindMe"
filename = "findme-3.0.6-forge.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3732/916/findme-3.0.6-forge.jar"
hash-format = "sha1"
hash = "1cb7703d4a53bc15dfde22a107bf1be576952e5b"

[update]
[update.curseforge]
file-id = 3732916
project-id = 291936
