name = "FPS Reducer"
filename = "FpsReducer2-forge-1.18.2-2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3680/770/FpsReducer2-forge-1.18.2-2.0.jar"
hash-format = "sha1"
hash = "90e5cfff15e6b50862073a16e5769fd05ab4d8e0"

[update]
[update.curseforge]
file-id = 3680770
project-id = 280294
