name = "FTB Library (Forge)"
filename = "ftb-library-forge-1802.3.6-build.115.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3725/485/ftb-library-forge-1802.3.6-build.115.jar"
hash-format = "sha1"
hash = "6fddfcee970cd3905809c9db64677399219e0f09"

[update]
[update.curseforge]
file-id = 3725485
project-id = 404465
