name = "GeckoLib"
filename = "geckolib-1.18-forge-3.0.14.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3752/391/geckolib-1.18-forge-3.0.14.jar"
hash-format = "sha1"
hash = "12201606cf25a51446c6f35cdb1c4262c5ecbff1"

[update]
[update.curseforge]
file-id = 3752391
project-id = 388172
