name = "GeckoLib"
filename = "geckolib-1.18-forge-3.0.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3785/773/geckolib-1.18-forge-3.0.18.jar"
hash-format = "sha1"
hash = "4dc93d8fe7b333ad4a7d2105d4dad8947ae0c419"

[update]
[update.curseforge]
file-id = 3785773
project-id = 388172
