name = "GeckoLib"
filename = "geckolib-1.18-forge-3.0.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3784/344/geckolib-1.18-forge-3.0.17.jar"
hash-format = "sha1"
hash = "b2f8c0c7d26d7ad0e7049ecf4390b0cb1ef25eaf"

[update]
[update.curseforge]
file-id = 3784344
project-id = 388172
