name = "Get It Together, Drops!"
filename = "getittogetherdrops-1.18.2-1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3683/767/getittogetherdrops-1.18.2-1.2.jar"
hash-format = "sha1"
hash = "be402042e81d92146742f06b2678a79ed65c04d8"

[update]
[update.curseforge]
file-id = 3683767
project-id = 411045
