name = "Immersive Engineering"
filename = "ImmersiveEngineering-1.18.2-8.0.1-147.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3755/665/ImmersiveEngineering-1.18.2-8.0.1-147.jar"
hash-format = "sha1"
hash = "819e13512bde891cea7e893b2cec3246e2789753"

[update]
[update.curseforge]
file-id = 3755665
project-id = 231951
