name = "Incendium"
filename = "Incendium_v5.0.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3682/938/Incendium_v5.0.3.jar"
hash-format = "sha1"
hash = "6c4a104cf8906e03fe1def251b1c7390fc1fca9d"

[update]
[update.curseforge]
file-id = 3682938
project-id = 591388
