name = "Just Enough Items (JEI)"
filename = "jei-1.18.2-9.7.0.193.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3758/750/jei-1.18.2-9.7.0.193.jar"
hash-format = "sha1"
hash = "2c466c5db37f07b428765ea34f065591a768a215"

[update]
[update.curseforge]
file-id = 3758750
project-id = 238222
