name = "Ksyxis"
filename = "Ksyxis-Forge1.17-1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3502/166/Ksyxis-Forge1.17-1.1.jar"
hash-format = "sha1"
hash = "15de04d92b32e1a62be953afeb25231cd36c954b"

[update]
[update.curseforge]
file-id = 3502166
project-id = 537533
