name = "Luggage"
filename = "luggage-1.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3763/261/luggage-1.2.jar"
hash-format = "sha1"
hash = "ea677632e2942bb138e5c66d8208363bc18419ff"

[update]
[update.curseforge]
file-id = 3763261
project-id = 594709
