name = "Luggage"
filename = "luggage-1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3752/66/luggage-1.1.jar"
hash-format = "sha1"
hash = "50aa4828fa0c5bb0594ab182ab9cf0f52fece4b4"

[update]
[update.curseforge]
file-id = 3752066
project-id = 594709
