name = "Luggage"
filename = "luggage-1.3.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3776/201/luggage-1.3.jar"
hash-format = "sha1"
hash = "247050d17ea1b9325a5993d4dd50de7ad4808866"

[update]
[update.curseforge]
file-id = 3776201
project-id = 594709
