name = "Mahou Tsukai"
filename = "mahoutsukai-1.18.2-v1.34.13.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3785/583/mahoutsukai-1.18.2-v1.34.13.jar"
hash-format = "sha1"
hash = "b864bad53604e89e7388596a51918bb586bedfb2"

[update]
[update.curseforge]
file-id = 3785583
project-id = 342543
