name = "Malum"
filename = "malum-1.18.2-1.3.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3768/401/malum-1.18.2-1.3.5.jar"
hash-format = "sha1"
hash = "a4f349d142b356b7c9755bec88b7bc6db9224d85"

[update]
[update.curseforge]
file-id = 3768401
project-id = 484064
