name = "Mantle"
filename = "Mantle-1.18.2-1.9.20.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3784/500/Mantle-1.18.2-1.9.20.jar"
hash-format = "sha1"
hash = "669698109b979cf01a26b88fbf3fab85710a8b82"

[update]
[update.curseforge]
file-id = 3784500
project-id = 74924
