name = "McJtyLib"
filename = "mcjtylib-1.18-6.0.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3725/413/mcjtylib-1.18-6.0.12.jar"
hash-format = "sha1"
hash = "d4e51923afc4cde72d0e85cf082ab82ea083710c"

[update]
[update.curseforge]
file-id = 3725413
project-id = 233105
