name = "Mekanism Generators"
filename = "MekanismGenerators-1.18.2-10.2.0.459.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3743/837/MekanismGenerators-1.18.2-10.2.0.459.jar"
hash-format = "sha1"
hash = "a12d1d445d2f25980d8fa66810eeb223a1fe3404"

[update]
[update.curseforge]
file-id = 3743837
project-id = 268566
