name = "Mekanism"
filename = "Mekanism-1.18.2-10.2.0.459.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3743/835/Mekanism-1.18.2-10.2.0.459.jar"
hash-format = "sha1"
hash = "b1e1f477dcde91764f8f0eae1dcc535a019d0d17"

[update]
[update.curseforge]
file-id = 3743835
project-id = 268560
