name = "Mekanism Additions"
filename = "MekanismAdditions-1.18.2-10.2.0.459.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3743/840/MekanismAdditions-1.18.2-10.2.0.459.jar"
hash-format = "sha1"
hash = "ec190fa1477469e6139a410c8776ded9a436fa86"

[update]
[update.curseforge]
file-id = 3743840
project-id = 345425
