name = "Mekanism Tools"
filename = "MekanismTools-1.18.2-10.2.0.459.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3743/838/MekanismTools-1.18.2-10.2.0.459.jar"
hash-format = "sha1"
hash = "cf461124be79bee62d1644007abec5187d2788e0"

[update]
[update.curseforge]
file-id = 3743838
project-id = 268567
