name = "Modular Force Fields Systems"
filename = "Modular Forcefields-1.18.2-0.0.1-2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3768/792/Modular%20Forcefields-1.18.2-0.0.1-2.jar"
hash-format = "sha1"
hash = "461e38e22c9fe186ed610bf20ae8ef3f6483826d"

[update]
[update.curseforge]
file-id = 3768792
project-id = 322896
