name = "Modular Force Fields Systems"
filename = "Modular Forcefields-1.18.2-0.0.1-1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3756/859/Modular%20Forcefields-1.18.2-0.0.1-1.jar"
hash-format = "sha1"
hash = "365f7b4db070abe34fdd80eff9f0c3efdf066cfe"

[update]
[update.curseforge]
file-id = 3756859
project-id = 322896
