name = "Mystical Adaptations"
filename = "MysticalAdaptations-1.18.2-1.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3706/862/MysticalAdaptations-1.18.2-1.1.1.jar"
hash-format = "sha1"
hash = "c67744278b1172df7aa2ed9d3bcc2a42a89f45f2"

[update]
[update.curseforge]
file-id = 3706862
project-id = 325892
