name = "Mystical Agriculture"
filename = "MysticalAgriculture-1.18.2-5.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3686/412/MysticalAgriculture-1.18.2-5.1.0.jar"
hash-format = "sha1"
hash = "14c809535abe2597cfb716e1a8f251fbd2751329"

[update]
[update.curseforge]
file-id = 3686412
project-id = 246640
