name = "Mystical Agradditions"
filename = "MysticalAgradditions-1.18.2-5.1.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3741/99/MysticalAgradditions-1.18.2-5.1.1.jar"
hash-format = "sha1"
hash = "795f4261232be4c27ad515c9c2c3f8a423c61b18"

[update]
[update.curseforge]
file-id = 3741099
project-id = 256247
