name = "Nuclear Science"
filename = "Nuclear Science-1.18.2-0.4.8-9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3775/474/Nuclear%20Science-1.18.2-0.4.8-9.jar"
hash-format = "sha1"
hash = "819087cfbf4ee53933c3b5b991b75920c89c23ae"

[update]
[update.curseforge]
file-id = 3775474
project-id = 318646
