name = "Occultism"
filename = "occultism-1.18.2-1.33.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3770/489/occultism-1.18.2-1.33.0.jar"
hash-format = "sha1"
hash = "76e7728eed32622bd912d8a94c6a8dcc9e8d1638"

[update]
[update.curseforge]
file-id = 3770489
project-id = 361026
