name = "Occultism"
filename = "occultism-1.18.2-1.30.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3759/406/occultism-1.18.2-1.30.1.jar"
hash-format = "sha1"
hash = "b9f6e62855ea8cff82111271cd953d64a1459505"

[update]
[update.curseforge]
file-id = 3759406
project-id = 361026
