name = "Occultism"
filename = "occultism-1.18.2-1.32.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3763/424/occultism-1.18.2-1.32.0.jar"
hash-format = "sha1"
hash = "9d296472a87178762cc30f3724eef1fa72e349a0"

[update]
[update.curseforge]
file-id = 3763424
project-id = 361026
