name = "Oculus"
filename = "oculus-mc1.18.2-1.2.2b.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3749/91/oculus-mc1.18.2-1.2.2b.jar"
hash-format = "sha1"
hash = "502159079ad4a0187d66e2735d3d6c9863d08628"

[update]
[update.curseforge]
file-id = 3749091
project-id = 581495
