name = "OpenBlocks Elevator"
filename = "elevatorid-1.18.2-1.8.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3670/34/elevatorid-1.18.2-1.8.4.jar"
hash-format = "sha1"
hash = "c32376d6741c1f8ec4ed637bb55e070c3ad3200e"

[update]
[update.curseforge]
file-id = 3670034
project-id = 250832
