name = "OrtusLib"
filename = "ortus-1.18.2-1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3768/197/ortus-1.18.2-1.0.jar"
hash-format = "sha1"
hash = "8c1a8c7beea769b38c088f4fbb92c105bfdd55d4"

[update]
[update.curseforge]
file-id = 3768197
project-id = 616457
