name = "Pam's HarvestCraft 2 - Food Core"
filename = "pamhc2foodcore-1.18.2-1.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3740/562/pamhc2foodcore-1.18.2-1.0.1.jar"
hash-format = "sha1"
hash = "0fa43e39c996365a1a55ec4484e4b9654b786a0c"

[update]
[update.curseforge]
file-id = 3740562
project-id = 372534
