name = "Patchouli"
filename = "Patchouli-1.18.2-67.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3729/975/Patchouli-1.18.2-67.jar"
hash-format = "sha1"
hash = "59e155f78560b0b0bbd7e44ed97a5006f68b2689"

[update]
[update.curseforge]
file-id = 3729975
project-id = 306770
