name = "Placebo"
filename = "Placebo-1.18.2-6.4.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3781/199/Placebo-1.18.2-6.4.0.jar"
hash-format = "sha1"
hash = "477c4c0194e28463b91a42d941cd5a0d5f290b87"

[update]
[update.curseforge]
file-id = 3781199
project-id = 283644
