name = "Plasmo Voice"
filename = "plasmovoice-forge-1.18-1.2.12.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3777/377/plasmovoice-forge-1.18-1.2.12.jar"
hash-format = "sha1"
hash = "79ecbcde185afcdd43879cafa0bff7b1efd8346a"

[update]
[update.curseforge]
file-id = 3777377
project-id = 467028
