name = "PneumaticCraft: Repressurized"
filename = "pneumaticcraft-repressurized-1.18.2-3.2.2-79.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3784/238/pneumaticcraft-repressurized-1.18.2-3.2.2-79.jar"
hash-format = "sha1"
hash = "ff2020bf4b0fd4696948fd96017e1f9089fe815e"

[update]
[update.curseforge]
file-id = 3784238
project-id = 281849
