name = "PneumaticCraft: Repressurized"
filename = "pneumaticcraft-repressurized-1.18.2-3.2.1-75.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3773/677/pneumaticcraft-repressurized-1.18.2-3.2.1-75.jar"
hash-format = "sha1"
hash = "3a0ddd0a17a21f07e8141c78280ca5275aced8c6"

[update]
[update.curseforge]
file-id = 3773677
project-id = 281849
