name = "Prefab"
filename = "prefab-1.8.2.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3763/476/prefab-1.8.2.1.jar"
hash-format = "sha1"
hash = "b1f68d1dbf69ab72f2c97b890b6422aee25d467f"

[update]
[update.curseforge]
file-id = 3763476
project-id = 246550
