name = "Prefab"
filename = "prefab-1.8.2.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3672/2/prefab-1.8.2.0.jar"
hash-format = "sha1"
hash = "acd9662a293cc4f98856e68ac08a535f13af17f3"

[update]
[update.curseforge]
file-id = 3672002
project-id = 246550
