name = "Quark"
filename = "Quark-3.2-355.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3783/383/Quark-3.2-355.jar"
hash-format = "sha1"
hash = "2a9f4b8d426dae268e54ecad24b4bbc0629dd75d"

[update]
[update.curseforge]
file-id = 3783383
project-id = 243121
