name = "Quark"
filename = "Quark-3.2-353.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3770/794/Quark-3.2-353.jar"
hash-format = "sha1"
hash = "51f509e181ab54b06a7b8a9fc74c5c5c6511804b"

[update]
[update.curseforge]
file-id = 3770794
project-id = 243121
