name = "Quark"
filename = "Quark-3.2-352.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3769/911/Quark-3.2-352.jar"
hash-format = "sha1"
hash = "589c1f87e7241225d53bb3c1bfc38d54a16cdcb2"

[update]
[update.curseforge]
file-id = 3769911
project-id = 243121
