name = "Quark Oddities"
filename = "QuarkOddities-1.18.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3575/623/QuarkOddities-1.18.jar"
hash-format = "sha1"
hash = "2d166f4d115360d6132a7bc277f4c6d47bb311ec"

[update]
[update.curseforge]
file-id = 3575623
project-id = 301051
