name = "Quark"
filename = "Quark-3.2-349.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3756/221/Quark-3.2-349.jar"
hash-format = "sha1"
hash = "330febbca726c0888286d8aa5bec85b2c0c91cbc"

[update]
[update.curseforge]
file-id = 3756221
project-id = 243121
