name = "RFTools Utility"
filename = "rftoolsutility-1.18-4.0.13.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3752/150/rftoolsutility-1.18-4.0.13.jar"
hash-format = "sha1"
hash = "3ae08bb9fd3719f4afb62c7c8cf48cb87dcc4ed5"

[update]
[update.curseforge]
file-id = 3752150
project-id = 342466
