name = "RFTools Power"
filename = "rftoolspower-1.18-4.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3711/547/rftoolspower-1.18-4.0.4.jar"
hash-format = "sha1"
hash = "9cebe1cd41bca9224c33b92229c6982498ca3899"

[update]
[update.curseforge]
file-id = 3711547
project-id = 290209
