name = "RFTools Builder"
filename = "rftoolsbuilder-1.18-4.0.9.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3752/154/rftoolsbuilder-1.18-4.0.9.jar"
hash-format = "sha1"
hash = "cc993e645b65406485ab7124b6884c103cb2f734"

[update]
[update.curseforge]
file-id = 3752154
project-id = 347706
