name = "RFTools Storage"
filename = "rftoolsstorage-1.18-3.0.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3771/412/rftoolsstorage-1.18-3.0.8.jar"
hash-format = "sha1"
hash = "44050293db4b5b3627729241388650b49bcd5572"

[update]
[update.curseforge]
file-id = 3771412
project-id = 350006
