name = "RFTools Dimensions"
filename = "rftoolsdim-1.18-8.0.4.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3720/439/rftoolsdim-1.18-8.0.4.jar"
hash-format = "sha1"
hash = "544ea0d40cc4dda47e89e4b5c9dd2d8d13b937cc"

[update]
[update.curseforge]
file-id = 3720439
project-id = 240950
