name = "RFTools Utility"
filename = "rftoolsutility-1.18-4.0.14.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3753/619/rftoolsutility-1.18-4.0.14.jar"
hash-format = "sha1"
hash = "b4cb7141973f331205d332af47dd72f7b05f62ae"

[update]
[update.curseforge]
file-id = 3753619
project-id = 342466
