name = "Roughly Enough Items Fabric/Forge (REI)"
filename = "RoughlyEnoughItems-8.1.457.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3768/210/RoughlyEnoughItems-8.1.457.jar"
hash-format = "sha1"
hash = "87c1cf2b8ecaa42256455eb94ea265d90b240aeb"

[update]
[update.curseforge]
file-id = 3768210
project-id = 310111
