name = "Rubidium"
filename = "rubidium-0.5.2a.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3749/94/rubidium-0.5.2a.jar"
hash-format = "sha1"
hash = "f2104b404a0508daa1b362de9a491b69aaf26175"

[update]
[update.curseforge]
file-id = 3749094
project-id = 574856
