name = "Runelic"
filename = "Runelic-Forge-1.18.2-11.0.1.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3683/668/Runelic-Forge-1.18.2-11.0.1.jar"
hash-format = "sha1"
hash = "7b0e74b79b307be15a05f50a173e3396363b687a"

[update]
[update.curseforge]
file-id = 3683668
project-id = 393149
