name = "Smooth Chunk Save[Forge/Fabric]"
filename = "smoothchunk-1.18.2-1.8.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3784/442/smoothchunk-1.18.2-1.8.jar"
hash-format = "sha1"
hash = "1659afb1d4145b13e1f6c2229575788b1bf6b950"

[update]
[update.curseforge]
file-id = 3784442
project-id = 582327
