name = "Starlight (Forge)"
filename = "starlight-1.0.2+forge.546ae87.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3706/539/starlight-1.0.2+forge.546ae87.jar"
hash-format = "sha1"
hash = "c7dde83f5fbc864d85842c74a4433a8a5c0f15b7"

[update]
[update.curseforge]
file-id = 3706539
project-id = 526854
