name = "Technical Electrical Resources"
filename = "TER.zip"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3755/117/TER.zip"
hash-format = "sha1"
hash = "b4d19afc991a78d2de5d12f4bfd1e7e001729cb9"

[update]
[update.curseforge]
file-id = 3755117
project-id = 389642
