name = "Terralith"
filename = "Terralith_v2.2.1a.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3696/607/Terralith_v2.2.1a.jar"
hash-format = "sha1"
hash = "6fc7c336beb04b72adae9323e7e7814ed3a02c09"

[update]
[update.curseforge]
file-id = 3696607
project-id = 513688
