name = "The One Probe"
filename = "theoneprobe-1.18-5.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3671/753/theoneprobe-1.18-5.1.0.jar"
hash-format = "sha1"
hash = "c0b89eb8740c94dfcb0fbec9d4c6bb13bbbe9f33"

[update]
[update.curseforge]
file-id = 3671753
project-id = 245211
