name = "Tinkers Construct"
filename = "TConstruct-1.18.2-3.5.0.17.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3784/732/TConstruct-1.18.2-3.5.0.17.jar"
hash-format = "sha1"
hash = "de78d2343b84c4b5a99748dde52ce0d34e281209"

[update]
[update.curseforge]
file-id = 3784732
project-id = 74072
