name = "Xaero's Minimap (Fair-play Edition)"
filename = "Xaeros_Minimap_FP22.4.0_Forge_1.18.2.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3728/390/Xaeros_Minimap_FP22.4.0_Forge_1.18.2.jar"
hash-format = "sha1"
hash = "687675d9805fa05667529f64bce9ad5abc8d82ff"

[update]
[update.curseforge]
file-id = 3728390
project-id = 263466
