name = "XNet"
filename = "xnet-1.18-4.0.5.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3711/553/xnet-1.18-4.0.5.jar"
hash-format = "sha1"
hash = "5ed5b1e4edfc3df3dcd521b8db3eb183e8e9c625"

[update]
[update.curseforge]
file-id = 3711553
project-id = 260912
