name = "YUNG's Bridges (Forge)"
filename = "YungsBridges-1.18.2-Forge-2.1.0.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3777/944/YungsBridges-1.18.2-Forge-2.1.0.jar"
hash-format = "sha1"
hash = "c3a4dca025adead5b297a403cc3b03e71d8e739b"

[update]
[update.curseforge]
file-id = 3777944
project-id = 536660
