name = "ZeroCore 2"
filename = "ZeroCore2-1.18.2-2.1.16.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3768/542/ZeroCore2-1.18.2-2.1.16.jar"
hash-format = "sha1"
hash = "30e012ba4e2ae8c0a4b0037312d1466d76596592"

[update]
[update.curseforge]
file-id = 3768542
project-id = 247921
