name = "ZeroCore 2"
filename = "ZeroCore2-1.18.2-2.1.15.jar"
side = "both"

[download]
url = "https://edge.forgecdn.net/files/3681/549/ZeroCore2-1.18.2-2.1.15.jar"
hash-format = "sha1"
hash = "3a71b9f8f9411959172d31f6db2c1e96fe3d28da"

[update]
[update.curseforge]
file-id = 3681549
project-id = 247921
